name: CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIBABA_REGISTRY }}
          username: ${{ secrets.ALIBABA_USERNAME }}
          password: ${{ secrets.ALIBABA_PASSWORD }}

      - name: Extract branch or tag name
        shell: bash
        run: echo "REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Build and push dev Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ALIBABA_REGISTRY }}/dev/vp_front:${{ env.REF_NAME }}-dev
          build-args: |
            RELEASE_ENV=dev

      - name: Restart Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
        with:
          args: rollout restart deployment/${{ env.DEPLOYMENT_NAME }}
